<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-27T17:21:06 IST" name="Suite" finished-at="2024-04-27T17:21:07 IST" duration-ms="891">
    <groups>
      <group name="purchase">
        <method signature="submitOrderTest.submitOrder(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Framework_Tutorial.submitOrderTest@22555ebf]" name="submitOrder" class="Framework_Tutorial.submitOrderTest"/>
      </group> <!-- purchase -->
    </groups>
    <test started-at="2024-04-27T17:21:06 IST" name="error Message Testing" finished-at="2024-04-27T17:21:06 IST" duration-ms="24">
    </test> <!-- error Message Testing -->
    <test started-at="2024-04-27T17:21:06 IST" name="submit Order Testing" finished-at="2024-04-27T17:21:07 IST" duration-ms="762">
      <class name="Framework_Tutorial.submitOrderTest">
        <test-method signature="submitOrder(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Framework_Tutorial.submitOrderTest@22555ebf]" started-at="2024-04-27T17:21:06 IST" name="submitOrder" data-provider="getData" finished-at="2024-04-27T17:21:07 IST" duration-ms="723" status="FAIL">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
[public void Framework_Tutorial.submitOrderTest.submitOrder(java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: submitOrder([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2])
Arguments: [(java.util.HashMap) {password=Varsha#1, product=ZARA COAT 3, email=vkharage@gmail.com}]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void Framework_Tutorial.submitOrderTest.submitOrder(java.lang.String,java.lang.String,java.lang.String) throws java.io.IOException] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: submitOrder([java.lang.String arg0, java.lang.String arg1, java.lang.String arg2])
Arguments: [(java.util.HashMap) {password=Varsha#1, product=ZARA COAT 3, email=vkharage@gmail.com}]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:46)
at org.testng.internal.Parameters.injectParameters(Parameters.java:918)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
      </class> <!-- Framework_Tutorial.submitOrderTest -->
    </test> <!-- submit Order Testing -->
  </suite> <!-- Suite -->
</testng-results>
